# Read the Docs configuration file for MkDocs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the OS, Python version, and build tool
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Build documentation using MkDocs
mkdocs:
  configuration: mkdocs.yml

# Install MkDocs and theme dependencies
python:
  install:
    - requirements: docs/requirements.txt